### ISSUE TITLE
Handle errors of "File not found"

### ISSUE THREAD

**Issue by barbushin** [barbushin/javascript-errors-notifier#1]

**Comment by pjvandehaar** [comment]
Is this something like

```javascript
chrome.webRequest.onCompleted.addListener(function (details) {
    if (details.statusCode == 404) { //TODO: check for 4XX? Others?
        //Show the PageAction
    }
});
```

[Documenation](https://developer.chrome.com/extensions/webRequest#event-onCompleted)

**Comment by barbushin** [comment]
Hey guys! Check this out https://github.com/barbushin/javascript-errors-notifier/commit/7f77903d0b7550fc7110170b7d21009a31ed71b8

I deployed test version here https://chrome.google.com/webstore/detail/fhbooopdkjpkogooopbmabepipljagfn Could you please give me some feedback if it works for you?

**Comment by pjvandehaar** [comment]
This is working well for me. (2.2.0– I haven't tried the new commit)

**Comment by barbushin** [comment]
Fixed.
