### ISSUE TITLE
Catching javascript errors in a extension

### ISSUE THREAD

**Issue by jeffg2k** [barbushin/javascript-errors-notifier#11]
This is not a issue with javascript-errors-notifier, but I don't see that GitHub has a way to send you a message.  So, sorry for the intrusion here with this related question.  Maybe you could spin this off into another script, but I'm struggling to find an easy way to catch the uncaught exceptions in a Chrome Extension.  I have an Extension and I'd like to be able to offer the user the option of sending me a bug report with the trace when an exception occurs, but can't figure out how to get it.  window.onerror doesn't seem to work.  Is there some special magic that needs to be done to catch the global exceptions of the extension itself?  It seems you got it figure out.

**Comment by barbushin** [comment]
There is open source solution to do this https://github.com/getsentry/sentry
Cheers!
