### ISSUE TITLE
Error is undefined because this method as protected

### ISSUE THREAD

**Issue by ivanferrer** [barbushin/javascript-errors-notifier#13]
CustomError: Error in protected function: undefined
https://talkgadget.google.com/_/scs/talk-static/_/js/k=wcs.wbl.pt_BR.3IwF77ShqK4.O/m=b,bst,cnv,ca,md,r/am=LITgq4ADUYAB/rt=j/d=1/t=zcms/rs=AItRSTPvkts9VhqBA9OMBsjgAbx4teCV8Q

**Comment by barbushin** [comment]
Cannot reproduce.
