### ISSUE TITLE
help i am havingt problems controling my chrome book

### ISSUE THREAD

**Issue by j11611** [barbushin/javascript-errors-notifier#14]
please help this is not a joke

**Comment by barbushin** [comment]
What problem?

**Comment by j11611** [comment]
Which problem aaree yyou refferiong to (i did not type thwat<)I found beta more stablee ( the typing erroesoccour depending on where inam aat)The 1st 14 lines of my O.S were corput in beta soi go to stable aand hings just (speell Checckingjust appeard)wworse ithink i will go back to betaI wwould loe to try the devlopers channel the moree i type the wworse the spelling gets even on word i allready typed thhere getting changed  also ( thats a new one on mee)the first 14 in this one seems to bee thee samee in stable?as thheey were in betaa.Thee day i left that smpoething was harresindg me biggtime in here.Inhaa taken aa screen shot of  someetthing andd apperently some boddydidnotlike that i was harresd until thheey gotit back took it out of my G drive wow nojoking here.j11611.iwaws even in the hangouts with Googgle annd  as thing s were ocurringthta was a bit oof a shocker.Iaam at least going back to beta.James
