### ISSUE TITLE
G drive(being blocked from it's use)

### ISSUE THREAD

**Issue by j11611** [barbushin/javascript-errors-notifier#16]
I am being blocked from using my G Drive ssince it is a Google page i cannot use the camera on the computer but i do indeed have pictures of the JVS errors. j1611.

**Comment by barbushin** [comment]
Is JavaScript Errors Notifier is corresponding to that problem?

**Comment by j11611** [comment]
Sorry to be brief but yes it is.

**Comment by barbushin** [comment]
I don't understand what is your problem, and what do you want.

**Comment by j11611** [comment]
I can put files into my drive but,I am being blocked from opening them.
