### ISSUE TITLE
Text overlapping in JEN address bar popup

### ISSUE THREAD

**Issue by arfmach** [barbushin/javascript-errors-notifier#18]
Hello. I've opened JEN popup in a website and link texts overlapped. I needed to inspect elements to understand what they meant.

Here is a screenshot of the popup.

![javascript errors notifier - overlap](https://cloud.githubusercontent.com/assets/7331118/8166694/cbe651b0-136f-11e5-8960-6e2b3599d138.png)

**Comment by barbushin** [comment]
Hi. Could you please attach URL of that page?

**Comment by ratisoctavian** [comment]
same to me, on almost all internal sites.

**Comment by codankserkan** [comment]
Same issue!

**Comment by barbushin** [comment]
Fix is coming. 10 min..

**Comment by barbushin** [comment]
I deployed 2.1.10 fixed version. It will be verified by Google in about 1 hour, and then going to update in users browsers. You can force update by clicking Update button on `chrome://extensions/` page, but before check that published JEN version on https://chrome.google.com/webstore/detail/javascript-errors-notifie/jafmfknfnkoekkdocjiaipcnmkklaajd is >= `2.1.10`.

Sorry for that bug. Next time I'll test it twice before deploying :)

**Comment by barbushin** [comment]
BTW, are all of you guys are using Mac OS?

**Comment by codankserkan** [comment]
mine is Windows 7.

**Comment by barbushin** [comment]
Ok, guys. Looks like everything works fine for now. I'm closing issue. 
Thanks for report!
