### ISSUE TITLE
Error warning on every page with or without errors #bug

### ISSUE THREAD

**Issue by zhgabor** [barbushin/javascript-errors-notifier#19]
Problem with warning indicator, its always ON even when there are no errors on the page.
![untitled-3](https://cloud.githubusercontent.com/assets/12900744/8168718/710cf0bc-13ad-11e5-8dd8-3d1a73258179.jpg)
please fix

**Comment by barbushin** [comment]
Fix is coming.

**Comment by zhgabor** [comment]
thanks, i really love your plugin

**Comment by barbushin** [comment]
I deployed `2.1.10` fixed version. It will be verified by Google in about 1 hour, and then going to update in users browsers. You can force update by clicking Update button on `chrome://extensions/` page, but before check that published JEN version on https://chrome.google.com/webstore/detail/javascript-errors-notifie/jafmfknfnkoekkdocjiaipcnmkklaajd is >= `2.1.10`.

Sorry for that bug. Next time I'll test it twice before deploying :)

**Comment by barbushin** [comment]
BTW, are all of you guys are using Mac OS?

**Comment by zhgabor** [comment]
me: win 7/8
