### ISSUE TITLE
Text overlapping in JEN address bar popup

### ISSUE THREAD

**Issue by codankserkan** [barbushin/javascript-errors-notifier#20]
https://github.com/barbushin/javascript-errors-notifier/issues/18#issuecomment-112180741
<img src='https://cloud.githubusercontent.com/assets/7331118/8166694/cbe651b0-136f-11e5-8960-6e2b3599d138.png' /> 
This issue start again!

**Comment by barbushin** [comment]
Fixed 30 minutes ago https://github.com/barbushin/javascript-errors-notifier/issues/21 Sorry about that. And thanks for report!
