### ISSUE TITLE
Error being reported on every pag

### ISSUE THREAD

**Issue by dan-drews** [barbushin/javascript-errors-notifier#23]
There appears to be a bug that has crept in and out repeatedly where every page has an error, and the error details are blank (the exclamation point appears in the URL bar on every page) even when there is no JS error

**Comment by Zopitirik** [comment]
Same as here. Everypage has an error.

**Comment by barbushin** [comment]
Hey. Open `chrome://extensions/?id=jafmfknfnkoekkdocjiaipcnmkklaajd` in Chrome and check that extension version is >= `2.1.14`. Otherwise try to reinstall it.

**Comment by dfibuch** [comment]
Was getting the same thing and @barbushin's suggestion works. I was running 2.1.11

**Comment by Zopitirik** [comment]
I was using 2.1.15 and no available update.
So tried to reinstall. It returned to normal. ty @barbushin
