### ISSUE TITLE
Not detecting AngularJS errors

### ISSUE THREAD

**Issue by hcoupet** [barbushin/javascript-errors-notifier#27]
Not detecting AngularJS Errors

**Comment by barbushin** [comment]
Hi. Sorry for late response. Could you please provide screenshot of expanded error data in Chrome JavaScript Console that is not handled by JEN?

**Comment by brunotiago** [comment]
Same issue here. Angular exceptions do not appear on extension.

**Comment by barbushin** [comment]
Could you please provide screenshot of expanded error data in Chrome JavaScript Console that is not handled by JEN or URL of the page?

**Comment by brunotiago** [comment]
It is because Angular do not throw the exceptions to the console. I fixed using these two pages of Angular manual:

https://docs.angularjs.org/api/ng/service/$exceptionHandler

https://docs.angularjs.org/guide/bootstrap

If you need any help, please tell

**Comment by barbushin** [comment]
@brunotiago Could you please send link to some Angular page with error? Thank you!

**Comment by barbushin** [comment]
Fixed.
