### ISSUE TITLE
Options page

### ISSUE THREAD

**Issue by fraserredmond** [barbushin/javascript-errors-notifier#29]
Can the options be moved out of the small popup into an actual Options page? When setting up a new computer I want to enable the toasters during setup/install, instead I currently have to remember to right-click the red icon the next time I see it (or break one of my pages to force the error notification.)

If you're feeling lazy the options page could even just cause an error, and have an arrow on it to say to set the options in the popup.

**Comment by barbushin** [comment]
Hi. I will try to devel it later, when I'll have a free time. For now you can just go to http://php-console.com/instance/examples/#handle_javascript_errors to force JEN icon displaying in address bar.
