### ISSUE TITLE
Everytime the page is refreshed the java scripts are disabled

### ISSUE THREAD

**Issue by sudipto1989** [barbushin/javascript-errors-notifier#30]
As soon as the page is refreshed or lands to a new page the embedded Java scripts are disabled and thus when the code runs/executes certain elements are not recognized and thus the error.

Actual annotation/code:
    <link type="text/css" rel="stylesheet" href="../css/ui-tooltip.css" /><link type="text/css" rel="stylesheet" href="../css/layoutWBEReport.css" />
    <script src="../Scripts/modernizr.js" type="text/javascript"></script>
    <script type="text/javascript" src="../Scripts/jquery.tools.min.js"></script>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js"></script>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.0/jquery-ui.min.js"></script>
    <script type="text/javascript" src="../Scripts/json2.js"></script>
    <script type="text/javascript" src="../Scripts/jquery.maskedinput-1.3.min.js"></script>
    <script type="text/javascript" src="../Scripts/validator_v4.js"></script>
    <script type="text/javascript" src="../Scripts/jquery.labelify.js"></script>
    <script type="text/javascript" src="/globalJSIncludes/centeredWindow.js"></script>
    <script type="text/javascript" src="../Scripts/Functions.js"></script>
      

Issue:
ReferenceError: Modernizr is not defined
#6 http://staging.quotit.net/quotit/apps/epro/infoEntry/infoEntry.aspx?pageAction=GetQuote&license_no=RFY768&stateCountyID=NV&countyID=10247&zipCode=89119&covTypeID=EF&insuranceTypeID=H&bSubmitted=0&wordOfTheDay=fulmination&isMedicare=&selectedPeriodID=&source=&remoteSourceKey=&owner=quotit&planTypeID=%&doPlanFinder=0&externalID=&layout=&brokerID=70466&bUsingLeads=False&report=IFPReport3&familySourceReferenceID=&infoEntryLayout=4&isPostBack=1&leadSourceKey=:1287:14
#5 http://staging.quotit.net/quotit/apps/epro/infoEntry/infoEntry.aspx?pageAction=GetQuote&license_no=RFY768&stateCountyID=NV&countyID=10247&zipCode=89119&covTypeID=EF&insuranceTypeID=H&bSubmitted=0&wordOfTheDay=fulmination&isMedicare=&selectedPeriodID=&source=&remoteSourceKey=&owner=quotit&planTypeID=%&doPlanFinder=0&externalID=&layout=&brokerID=70466&bUsingLeads=False&report=IFPReport3&familySourceReferenceID=&infoEntryLayout=4&isPostBack=1&leadSourceKey=:1287:14 HTMLDocument.()
#4 http://ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js:2:16934 k()
#3 http://ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js:2:17721 Object.l.fireWith [as resolveWith]()
#2 http://ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js:2:12438 Function.p.extend.ready()
#1 http://ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js:2:9843 HTMLDocument.D()

ReferenceError: infoEntry is not defined
#3 http://staging.quotit.net/quotit/apps/epro/infoEntry/infoEntry.aspx?pageAction=GetQuote&license_no=RFY768&stateCountyID=NV&countyID=10247&zipCode=89119&covTypeID=EF&insuranceTypeID=H&bSubmitted=0&wordOfTheDay=fulmination&isMedicare=&selectedPeriodID=&source=&remoteSourceKey=&owner=quotit&planTypeID=%&doPlanFinder=0&externalID=&layout=&brokerID=70466&bUsingLeads=False&report=IFPReport3&familySourceReferenceID=&infoEntryLayout=4&isPostBack=1&leadSourceKey=:1713:21
#2 http://staging.quotit.net/quotit/apps/epro/infoEntry/infoEntry.aspx?pageAction=GetQuote&license_no=RFY768&stateCountyID=NV&countyID=10247&zipCode=89119&covTypeID=EF&insuranceTypeID=H&bSubmitted=0&wordOfTheDay=fulmination&isMedicare=&selectedPeriodID=&source=&remoteSourceKey=&owner=quotit&planTypeID=%&doPlanFinder=0&externalID=&layout=&brokerID=70466&bUsingLeads=False&report=IFPReport3&familySourceReferenceID=&infoEntryLayout=4&isPostBack=1&leadSourceKey=:1713:21 AccordingToZipCodeShowState()
#1 http://staging.quotit.net/quotit/apps/epro/infoEntry/infoEntry.aspx?pageAction=GetQuote&license_no=RFY768&stateCountyID=NV&countyID=10247&zipCode=89119&covTypeID=EF&insuranceTypeID=H&bSubmitted=0&wordOfTheDay=fulmination&isMedicare=&selectedPeriodID=&source=&remoteSourceKey=&owner=quotit&planTypeID=%&doPlanFinder=0&externalID=&layout=&brokerID=70466&bUsingLeads=False&report=IFPReport3&familySourceReferenceID=&infoEntryLayout=4&isPostBack=1&leadSourceKey=:3913:100 HTMLInputElement.onkeyup()

Actual code is attached.

**Comment by barbushin** [comment]
Can you attach URL of this page?

**Comment by sudipto1989** [comment]
there was an issue with the connection which was causing this issue.
Updating the URL to https resolved the issue.
With https the native script were accessible from the browser and thus the expected scripts were successfully run and the issue was no longer seen
