### ISSUE TITLE
javascript-errors-notifier

### ISSUE THREAD

**Issue by chanachon2819** [barbushin/javascript-errors-notifier#33]

**Comment by barbushin** [comment]
Spam?

**Comment by Tryptich** [comment]
not, it's not a spam. but i have saw that the bug i have seen , was already
resolve.




*TUENKAM STEVE MASTER STUDENT,*

*In Computer Science Departement *

*University of Yaounde 1, Cameroon*

2015-11-28 15:22 GMT+01:00 Sergey <notifications@github.com>:
