### ISSUE TITLE
Undefined variables

### ISSUE THREAD

**Issue by TopDog1691** [barbushin/javascript-errors-notifier#34]
ReferenceError: cmSetClientID is not defined
https://www.usa.canon.com/NewWebThemeStatic/themes/NewWebTheme/js/coreMetricsWrapper.js:90

ReferenceError: cmCreatePageviewTag is not defined
https://www.usa.canon.com/NewWebThemeStatic/themes/NewWebTheme/js/coreMetricsWrapper.js:39

ReferenceError: cmCreateElementTag is not defined
https://www.usa.canon.com/NewWebThemeStatic/themes/NewWebTheme/js/coreMetricsWrapper.js:54

As reported by Chrome from this url:
https://www.usa.canon.com/internet/portal/us/home/!ut/p/z1/hY8xD4IwEIV_iwOjvYsYgm6IMWh0cFHsYgqB0gSupBSUf2_VVcPb3r3vXu6AQwqcxKCksEqTqJ2_8eB-Oidhso_xiJfNEqNgtY39xQ6d4DoFcBfjH0XvfT6FHIDLWmffayLK_FACN0VZmMKw3rhxZW279tDD1iiyiqQi0sPnh47lfSdYLkgTy3XjYSOeqhx_dVW6s5BOd0DbpDjn2fiIZrMXfdS29A!!/dz/d5/L2dBISEvZ0FBIS9nQSEh/?cm_mmc=printer-_-ref-site-_-printing-innovations-_-canon-logo-globhead

**Comment by barbushin** [comment]
JEN can handle only errors that are handled by Chrome. But Chrome does not handle any errors on this page http://vgy.me/SC8ATc.jpg so... 

Sorry, I'm not sure that I can understand what is the problem and how to fix it.

Please reopen issue with more details.
