### ISSUE TITLE
Easier way to configure "Show Notification Popups for Errors" setting

### ISSUE THREAD

**Issue by felickz** [barbushin/javascript-errors-notifier#35]
Please give a way to configure "show notification popups for XYZ domain" BEFORE you get an error and can click on the toolbar icon. Not obvious how you would do this first time without an error. Potentially an OPTIONS link in the Chrome Extensions list?

**Comment by barbushin** [comment]
Okay. Coming soon.

**Comment by Tryptich** [comment]
thank's

**Comment by felickz** [comment]
Could you implement wildcards in the domain list

Ex if I want to have script errors for
- http://english.stackexchange.com/
- http://security.stackexchange.com/

Allow us to add *.stackoverflow.com

**Comment by barbushin** [comment]
@felickz Sure. Please create new issue.
