### ISSUE TITLE
Handle console.error & console.warn calls

### ISSUE THREAD

**Issue by jrnail23** [barbushin/javascript-errors-notifier#37]
Does this tool only report unhandled errors, or does it also report error messages and warning messages written to the console (`console.warn`, `console.error`, etc.)?
(if not, it would be really great if it could)

**Comment by barbushin** [comment]
Great idea! I just tested it, and I see that it's very easy to override standard `console.*` functions. I'll implement it soon, when I have some free time.

**Comment by jrnail23** [comment]
@barbushin, thanks for the quick reply -- that feature would be really great for me and my team, as we test our React apps.
React writes warnings & errors to the console when you violate certain design/coding rules, and this would be a great way to make those problems more visible for us. :smile:

**Comment by barbushin** [comment]
I deployed v2.1.26 in Google WebStore. It's going to be reviewed by WebStore team and published in about 1 hour. Then it will take few hours before your Chrome will download new version. You can use `chrome://extensions/` to force updating to new version.

Please let me know if it works fine. Thanks!

**Comment by barbushin** [comment]
I deployed v2.1.26 in Google WebStore. It's going to be reviewed by WebStore team and published in about 1 hour. Then it will take few hours before your Chrome will download new version. You can use `chrome://extensions/` to force updating to new version.

Please let me know if it works fine. Thanks!

**Comment by jrnail23** [comment]
@barbushin, dude, you freaking rock. :100:

**Comment by dsherret** [comment]
This caused a lot of issues! `stack[3]` does not always match the regex in this code. For example, there is no parenthesis here:

```
"    at https://some-website-goes-here.net/Scripts/FloatingPanel.js:10:10"
```

When this fails, it throws an error that halts the execution of any code that uses `console.warn` and `console.error`. Websites like Jira are barely usable with this extension enabled.

I would highly suggest being a bit more defensive and fail silently (while still logging to the console) when there is an error in this extension.

**Comment by barbushin** [comment]
@dsherret But it's already fixed in https://github.com/barbushin/javascript-errors-notifier/commit/fe2be662e23ded1f484d3c68b6b2cba0995c255b Isn't it?

**Comment by barbushin** [comment]
@dsherret David, you was right. There was some another case with undefined index error. I fixed it in last commit and deployed in WebStore. Looks good for you?

**Comment by dsherret** [comment]
@barbushin yup, everything's working fine now. Thanks!
