### ISSUE TITLE
Websites do not render properly with latest update

### ISSUE THREAD

**Issue by bravotangooscar** [barbushin/javascript-errors-notifier#38]
I'm getting a number of errors that prevent pages from rendering properly with the new version published on 18 February. It seems to happen on pages that have console warnings that would normally be non-fatal. With the new version of the extension, the warnings are followed by an error along the lines of:
`Uncaught TypeError: Cannot read property 'someproperty' of null (someScriptfile.js)`
Disabling the extension causes the page to render normally.
* OS: Observed on OSX Mavericks and Windows 10
* Chrome Version:
  * OSX: 49.0.2623.54 beta (64-bit)
  * Win10: 49.0.2623.54 beta-m
* An example of a page that displays this behavior: https://issues.jenkins-ci.org/secure/Dashboard.jspa

Please let me know if I can provide any additional troubleshooting information.

**Comment by nbl9999** [comment]
what he said, same thing.

**Comment by barbushin** [comment]
Going to fix it right now.

**Comment by barbushin** [comment]
Just deployed fixed version 2.1.27. It will be available in 1 hour. You can force your browser to update on it in `chrome://extensions/`. Guys, please confirm that fix works for you.
![image](https://cloud.githubusercontent.com/assets/683352/13177415/f9c60b2c-d753-11e5-89d6-a50782d0bfeb.png)

**Comment by ninboy** [comment]
It's working fine now, the update was just published
![screenshot 2](https://cloud.githubusercontent.com/assets/34670/13179380/b24a2254-d6f1-11e5-9c15-94b8eb0a8078.png)

I had problems earlier today loading multiple pages, but now they are working fine.

**Comment by nbl9999** [comment]
Yep, update 2.1.27 fixes it. Thx!

**Comment by bravotangooscar** [comment]
`2.1.27` is working for me as well across all browsers. Thanks!
