### ISSUE TITLE
Today started receiving errors on console messages... :(

### ISSUE THREAD

**Issue by born2net** [barbushin/javascript-errors-notifier#39]
Today started receiving errors on console messages... :(
see below

Regards,
Sean

![capture](https://cloud.githubusercontent.com/assets/5090936/13181934/3900ddd2-d6e4-11e5-9203-0a99815dc5ec.PNG)

**Comment by barbushin** [comment]
Actually you're right. May be it was a bad idea to handle `console.warn()` as errors. Fix is coming.

**Comment by barbushin** [comment]
Fix is deployed. You need to wait 1 hour to update. 
![image](https://cloud.githubusercontent.com/assets/683352/13182111/2763b0b8-d76b-11e5-91d0-06dc6376662e.png)

Thanks for report!

**Comment by born2net** [comment]
tx yes this renders the tool unusable... and I loved it before...

**Comment by born2net** [comment]
maybe you can give it as an option... [x]

**Comment by barbushin** [comment]
Ok :) Please confirm that fix works for you, so I'll close the issue. Cheers!

**Comment by born2net** [comment]
will do

**Comment by born2net** [comment]
fixed!!!!!!!!!!!!!!!!!!!
tx
