### ISSUE TITLE
Blacklist/Whitelist by domain or URL pattern

### ISSUE THREAD

**Issue by usmonster** [barbushin/javascript-errors-notifier#4]
Thanks for the simple and useful extension!

It would be nice to have a way to specify on which sites the extension will or will not be active.

**Comment by devalphabeta** [comment]
Whitelisting sites is a lot more important then blacklisting sites.  As a developer, you only want to see errors on domains that you are writing code for.  So being able to whitelist domains is a "must have" feature.   It is absolutely annoying going onto other websites and seeing their javascript errors, which is probably 75% of sites.  This whitelist feature would be an excellent addition.

**Comment by barbushin** [comment]
@devalphabeta @usmonster Already implemented. See 
![image](https://cloud.githubusercontent.com/assets/683352/26285257/cec24472-3e54-11e7-9784-8a97dff75607.png)
