### ISSUE TITLE
Google disabled address bar icons

### ISSUE THREAD

**Issue by barbushin** [barbushin/javascript-errors-notifier#40]
Hi everybody,

Since Google Chrome 49 you can see that browser now displays all installed extensions icons in toolbar. Also they disabled address bar icons API.

So now JavaScript Errors Notifier icon is always displayed in toolbar as transparent grey icon. 

### Stupid Google Chrome team!

They even did not notified that [pageAction API](https://developer.chrome.com/extensions/pageAction) is deprecated, and did not updated official API documentation.

Users really hates this update https://www.reddit.com/r/chrome/comments/48kxix/why_are_disabled_extension_icons_showing_up_in

### Anyway

For now I'm going to develop new way of notifications that will be displayed as icon/tooltip/baloon inside page with error.

### Any ideas what is the best way to design it?

**Comment by pjvandehaar** [comment]
Your fix is pretty good.  I agree, a `position: fixed` popup with a close button is probably the best approach.  Stupid Google Chrome team!

**Comment by barbushin** [comment]
Here is a draft version of how new notification icon & popup will looks like (displayed in bottom right corner).
![image](https://cloud.githubusercontent.com/assets/683352/13778802/cefeac0c-eaf2-11e5-8027-e8b912b86b7f.png)

**Comment by barbushin** [comment]
Published in v3.0
