### ISSUE TITLE
Implement wildcards in the domain list

### ISSUE THREAD

**Issue by felickz** [barbushin/javascript-errors-notifier#41]
As an enhancement to #35 

Could you implement wildcards in the domain 

Ex if I want to have script errors for

http://english.stackexchange.com/
http://security.stackexchange.com/
Allow us to add *.stackoverflow.com

**Comment by barbushin** [comment]
Now domain-specified options for icon/notification displaying are always related to 2nd level domain. So if you enable icon/notification for domain.com, it will be also enabled for sub.abc.com and sub.sub.domain.com and etc. Also if you enable icon/notification for sub.sub.domain.com, it will work also for domain.com and all sub-domains.
