### ISSUE TITLE
Chrome has been running REALLY slow since the update to 49

### ISSUE THREAD

**Issue by richardmtl** [barbushin/javascript-errors-notifier#42]
At least, I *think* it's 49 that did it. I restart Chrome on OSX only once a week or so, so I'm not sure if the update caused the issue or not, but I noticed it at the same time that I noticed #40. In any case, through trial and error, I found that it was this extension that slowed my Chrome down to a crawl, on doing anything (new tabs, clicking a link, clicking a button, whatever). In Incognito I don't have the problem, and I confirmed it by turning off and on this extension. Any debug info I can provide, of some sort?

**Comment by barbushin** [comment]
Could you please attach JavaScript console data? It's very easy:

1. Open `chrome://extensions/?id=jafmfknfnkoekkdocjiaipcnmkklaajd` url in your Google Chrome.
2. Enable `Developer mode` & click on JavaScript Errors Notifier `background.html` link(see [screenshot](http://i.imgur.com/jmBvqBy.png)).
3. Open `Console` tab (see [screenshot](http://i.imgur.com/GuNAv1B.png)).
4. If there are some errors, then expand all blocks and copy console data to clipboard.

Thank you.

**Comment by richardmtl** [comment]
Well, I reactivated the extension, and it's been a couple of hours and I have no problems so far. I'm going to close this issue, but I'll let you know if it happens again (currently on Version 49.0.2623.87 (64-bit) for the record), and I'll include the console data as requested. Thanks!
