### ISSUE TITLE
Links like view-source:http://php-console.com/js_errors.html:6:9 don't work for me

### ISSUE THREAD

**Issue by pjvandehaar** [barbushin/javascript-errors-notifier#44]
I literally just get the view-source page for <http://php-console.com/js_errors.html:6:9>, which is garbage.

I added a fix to https://github.com/barbushin/javascript-errors-notifier/pull/45 .

**Comment by barbushin** [comment]
Fixed in 3.0.3. Will be published in 1hr. Thanks for report!
