### ISSUE TITLE
Not getting ANY notification, oddly

### ISSUE THREAD

**Issue by bigteejay** [barbushin/javascript-errors-notifier#50]
I can only imagine this is something I am doing wrong, but haven't figured it out after searching here on github, on the extension page on chrome store and googling!

I installed the extension in Chrome ("Version 49.0.2623.87 m").  I see the icon added in the upper right now.  I run some code that triggers an error (I know because if I open the developer tools console, I see it reported) but I never get a notification (popup on screen, or change in the display of the icon on the toolbar.)

I left all settings as they are and triggered the error, I changed a few of the settings and triggered the error, no feedback from this extension at all (as far as I can tell.)

I do get the errors on the test page, http://php-console.com/js_errors.html

What am I doing wrong?  I have this, "Page Ruler", and "Clear Cache" extensions added (though none of which have been used since I installed this, and still the problem persists.)

EDIT: Should this address be an issue (while developing)...
http://localhost:8000/
...could localhost, or port 8000 be problematic?  I wouldn't think so?

EDIT2: This must be something with my environment, I tried another similar extension and it doesn't work either. Though it doesn't trigger on your test page either (while it does still show in console)

**Comment by cotwitch** [comment]
Yeah, I also encounter this problem with any other than standard http port 80. If I run my application on port 443, 8080, 8000 or simply any other than 80, I'm able to see errors in console, but not in js notifier extension (in-page error icon don't appear etc...).

**Comment by cotwitch** [comment]
Maybe that problem is in getBaseHostByUrl method in file background.js .
It's due to that described method is unable to parse URL where http port is defined explicitly (i.e. ":443")

**Comment by apollo-13** [comment]
For me it's fixed in `8626545ca33a971f274805fd29845548067d39c7` .

**Comment by barbushin** [comment]
Issue is fixed in 3.0.9. Thanks for report!
