### ISSUE TITLE
Empty errors popup dialog if "Block third-party cookies and site data" enabled

### ISSUE THREAD

**Issue by barbushin** [barbushin/javascript-errors-notifier#54]
JavaScript Errors Notifier does not works if **Settings > Privacy > Content settings > Block third-party cookies and site data** is enabled. 

For now there is only one way to fix it: uncheck this option.

![image](https://cloud.githubusercontent.com/assets/683352/14307592/08435708-fc03-11e5-99e7-6e22230e23be.png)

Feel free to send pull request that will fix it, because right now I don't have a free time to work on this.

**Comment by himdel** [comment]
When clicking the bottom icon, an empty popup appears and an error pops up in the console:

```
popup.js:12 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at initOptionSwitcher (chrome-extension://iihnpeckfoopfonmeeeclmcfecbaafjn/popup.js:12:50)
    at HTMLDocument.<anonymous> (chrome-extension://iihnpeckfoopfonmeeeclmcfecbaafjn/popup.js:28:2)
```

Clicking the address bar icon works just fine, the popup contains the right info.

---

(assuming that's the right issue:)

Would it make sense to solve this by adding an option to disable the popup icon completely?

**Comment by barbushin** [comment]
It's a very special case, so I don't think that it will be possible to fix it without cutting JEN functionality.
