### ISSUE TITLE
Incorrect wrapper handler

### ISSUE THREAD

**Issue by WORMSS** [barbushin/javascript-errors-notifier#56]
Your wrapper for console.error expects that there will only ever be 1 parameter.

    window.console.error = function(text) {
        consoleErrorFunc.call(console, text);
        handleUserError(text);
    };

But I pass multiple arguments but they are being stripped off.

[**console.error(object [, object, …])**](https://developers.google.com/web/tools/chrome-devtools/debug/console/console-reference?hl=en#error)

I have done a quick fix in my local copy by using `consoleErrorFunc.apply(console, arguments);`

I am sure some people will say I am creeping scope with the arguments variable and blar blar blar, but it was my quick fix. 

- Colin.

**Comment by barbushin** [comment]
Fixed in 3.0.13. Thanks for report!
