### ISSUE TITLE
Request: Show 404 errors for all resource file types

### ISSUE THREAD

**Issue by joelcolucci** [barbushin/javascript-errors-notifier#57]
## Description
Currently the extension will report 404s thrown for missing CSS and JavaScript resources.

However the extension does not report 404s for missing HTML files (ex. Polymer) or images.

## Value added
Reporting 404s thrown for all resources will assist developers in identifying missing/deprecated links to all critical resources.

This would be of assistance during development and in QA.

**Comment by barbushin** [comment]
![image](https://cloud.githubusercontent.com/assets/683352/14594329/e3f12632-0567-11e6-8d94-1ea668fc0786.png)
There is option `Ignore missing images & etc files error` that is enabled by default. Did you tried to disable it?

**Comment by barbushin** [comment]
Regarding handling errors for some missing HTML files. Sometime it's not possible technically, but to be sure, I need some live example for tests. Please attach link of page where 404 error of some resource file is not handled by JSEN, then I can try to fix it.

**Comment by joelcolucci** [comment]
My apologies. I scanned through the options and somehow missed the option `Ignore missing images & etc files error`.

I only noted the missing HTML 404 when developing with Polymer/Web Components. Other than that scenario I don't think it's likely to run into HTML imports. If if I find a live example I will let you know!

Thanks for your time and assistance. Feel free to close.
