### ISSUE TITLE
error in script

### ISSUE THREAD

**Issue by jt3k** [barbushin/javascript-errors-notifier#60]
```
handleNewError (content.js:62)
(anonymous function) (content.js:95)
(anonymous function) (VM3223:51)

```

![2016-09-23 14 49 32](https://cloud.githubusercontent.com/assets/1261240/18784770/043b06fe-819d-11e6-84e0-b54308e1bef6.png)

**Comment by barbushin** [comment]
Could you please give me error where I can reproduce it?

**Comment by jt3k** [comment]
sorry, but it's no longer relevant. and I already forgot about this case.
