### ISSUE TITLE
An option to whitelist domains

### ISSUE THREAD

**Issue by CoenraadS** [barbushin/javascript-errors-notifier#64]
Hello

Great addon! However I only care about errors on localhost:xxxx

If I it would be possible to whitelist this domain, and ignore all others that would be great.

**Comment by chsergey** [comment]
Good idea

But it will be better to have "Ignore this domain" button) 
Like in AdBlock

**Comment by timmfin** [comment]
I believe this is already implemented. If you click on the icon in the toolbar, you can use the icons in the bottom of the popup to whitelist a single domain:

![](https://d3uepj124s5rcx.cloudfront.net/items/2d1l1I3c092l343a1k0t/Image%202017-03-22%20at%205.07.44%20PM.png)

**Comment by devalphabeta** [comment]
**Whitelisting** sites is a lot more important then blacklisting sites. As a developer, you only want to see errors on domains that you are writing code for. So being able to **whitelist** domains is a "must have" feature for developers. 

I don't care about javascript errors on sites I am surfing when I am not developing code,
It is absolutely annoying going onto other websites and seeing their javascript errors, which is probably 75% of sites. 

This **whitelist** feature would be an excellent addition.

**Comment by barbushin** [comment]
Guys, to whitelist some domain, just open it in new tab, then click on JEN icon in toolbar, and then click on popup or `(1)` icon to whitelist it.
