### ISSUE TITLE
content.js:62 Uncaught TypeError: Cannot read property 'url' of null

### ISSUE THREAD

**Issue by johannesjo** [barbushin/javascript-errors-notifier#76]
I keep getting this `content.js:62 Uncaught TypeError: Cannot read property 'url' of null`, which is referring to this line: `isWrongUrl = !error.url || error.url.indexOf('://') === -1;`

**Comment by barbushin** [comment]
What is URL of page that triggers this error?

**Comment by johannesjo** [comment]
It's happening on localhost:300.

**Comment by barbushin** [comment]
I need some way to reproduce this bug. Could you share zip archive of static version of this page (Ctrl/Cmd + S).

**Comment by johannesjo** [comment]
That's a little tricky, because it is an closed source application, but I'll try to extract a test case, once I'm back from vacation.

**Comment by barbushin** [comment]
@johannesjo is there any other errors in JS console?

**Comment by johannesjo** [comment]
Hey there! Sorry for taking my time getting back to you. I just checked again. I've no idea why, but the issue doesn't occur any more. I suspect it being related to a third party tracking script being loaded, which now has gotten an update.
