### ISSUE TITLE
Ignore list support

### ISSUE THREAD

**Issue by brunobatista** [barbushin/javascript-errors-notifier#8]
I think will be great if have a support for know erros like a list of ignore common errors. Projects like jQuery, AngularJS and others, have small issues where take days to solve.

**Comment by barbushin** [comment]
It's not so easy to implement. Because I'll need to keep this list up to date and update extension too often. Also I think users should know that they use some jQuery or Angular version that have some errors.

**Comment by brunobatista** [comment]
Ok @barbushin, thanks!
