### ISSUE TITLE
Breaks on a page that has Google invisible reCAPTCHA enabled

### ISSUE THREAD

**Issue by IanKemp** [barbushin/javascript-errors-notifier#84]
The [invisible reCAPTCHA](https://developers.google.com/recaptcha/docs/invisible) injects its own element into any page it is enabled on, as shown at https://stackoverflow.com/questions/44543157/how-to-hide-the-google-invisible-recaptcha-badge. Unfortunately this seems to break this extension with the following error:

`Uncaught TypeError: Cannot read property '_fromJEN' of null at content.js:210`

My guess is that a simple fix would be to change that line from:

`if(typeof event.data == 'object' && event.data._fromJEN) {`

to

`if(typeof event.data == 'object' && typeof event.data._fromJEN !== "undefined" && event.data._fromJEN) {`

**Comment by barbushin** [comment]
Could you please attach some URL that I can use to reproduce this bug?

**Comment by IanKemp** [comment]
@barbushin Navigate to https://www.google.com/recaptcha/api2/demo?invisible=true - despite the fact that there are no JS errors on that page, the error I've reported still appears in the JS console.

**Comment by barbushin** [comment]
Fixed. It will be deployed in next few hours.
